### ISSUE TITLE
List Hydra as an IC3 project

### ISSUE THREAD

**Issue by lorenzb** [bl4ck5un/ic3-website#149]
Link to project website: https://thehydra.io/

**Comment by sr-gi** [comment]
@lorenzb if you're OK with this I'll update it. Let me know if you'd like to make any change.

name: 'The Hydra Project'
challenges: correctness
description: Hydra is a cutting-edge Ethereum contract development framework for decentralized security and bug bounties rigorous cryptoeconomic security guarantees mitigating programmer and compiler error.

**Comment by lorenzb** [comment]
Thank you, looks good. Could we add a link to the website to the description?
