### ISSUE TITLE
Decentralization in Bitcoin and Ethereum from Hacking Distributed parsed twice

### ISSUE THREAD

**Issue by sr-gi** [bl4ck5un/ic3-website#170]
It looks like the last post from @el33th4x0r's  blog has been parsed twice in the website. @bl4ck5un Do you have any clue about how to fix it?

![image](https://user-images.githubusercontent.com/6665628/34980794-e0563d0c-faa5-11e7-992e-e17487013218.png)

**Comment by bl4ck5un** [comment]
Ah, that's because when a post is tagged both "bitcoin" and "ethereum", it gets fetched twice on the page.
