### ISSUE TITLE
Post: Three IC3-authored papers at BITCOIN 2018: https://fc18.ifca.ai/bitcoin/schedule.html and IC3 faculty member as co-chair (Ittay Eyal)

### ISSUE THREAD

**Issue by ajuels** [bl4ck5un/ic3-website#192]

**Comment by sr-gi** [comment]
I guess they are the following:

- Smart Contracts for Bribing Miners
- Paralysis Proofs: Safe Access-Structure Updates for Cryptocurrencies and More
- Egalitarian Society or Benevolent Dictatorship: The State of Cryptocurrency Governance

Can you confirm @ajuels?

**Comment by ajuels** [comment]
Yes!
