### ISSUE TITLE
IC3 Spring Retreat

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#210]
1) Please update the Retreat page: http://www.initc3.org/events/2018-05-10-IC3-Spring-Retreat-in-NYC.html 
[IC3.website.2018.Spring.Retreat.in.NYC April 16.docx](https://github.com/bl4ck5un/ic3-website/files/1917646/IC3.website.2018.Spring.Retreat.in.NYC.April.16.docx)

2) Update the Home page and the Upcoming Events page with the date to be "May 10, 2018". (not May 10-11).

**Comment by jimballingall** [comment]
I don't see the new Retreat page posted (#1 above). with the attachment 
[IC3.website.2018.Spring.Retreat.in.NYC April 16.docx](https://github.com/bl4ck5un/ic3-website/files/1922468/IC3.website.2018.Spring.Retreat.in.NYC.April.16.docx)

**Comment by bl4ck5un** [comment]
Hi Jim, It’s here: http://www.initc3.org/events/2018-05-10-IC3-Spring-Retreat-in-NYC.html

**Comment by jimballingall** [comment]
Thanks Fan!
