### ISSUE TITLE
Update for IC3 Spring 2018 Retreat page

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#212]
Please use the attachment for new page
[IC3.website.2018.Spring.Retreat.in.NYC.April.27.docx](https://github.com/bl4ck5un/ic3-website/files/1957186/IC3.website.2018.Spring.Retreat.in.NYC.April.27.docx)

**Comment by jimballingall** [comment]
Thanks

**Comment by bl4ck5un** [comment]
Done.
