### ISSUE TITLE
Updated Spring Retreat Agenda - please post

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#213]
Please post the latest version attached here.
[IC3 Spring Retreat Agenda .docx](https://github.com/bl4ck5un/ic3-website/files/1968671/IC3.Spring.Retreat.Agenda.docx)

**Comment by jimballingall** [comment]
Hi Fan, Sorry, one typo, the last session should be "Session 7". (Now, we have two Session 6's).

Thanks,

Jim

**Comment by bl4ck5un** [comment]
Fixed.

Fan

**Comment by jimballingall** [comment]
New update

[IC3 Spring Retreat Agenda - May 7.docx](https://github.com/bl4ck5un/ic3-website/files/1982341/IC3.Spring.Retreat.Agenda.-.May.7.docx)

**Comment by bl4ck5un** [comment]
I'm going to close this as #214 overwrites this.
