### ISSUE TITLE
Updated page for IC3 2018 Spring Retreat

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#215]
Please use this to replace this page - http://www.initc3.org/events/2018-05-10-IC3-Spring-Retreat-in-NYC.html

[IC3 2018 Spring Retreat Web page.docx](https://github.com/bl4ck5un/ic3-website/files/2002201/IC3.2018.Spring.Retreat.Web.page.docx)

**Comment by bl4ck5un** [comment]
Will get to this on Friday.

Fan

**Comment by sr-gi** [comment]
I can take care of it @bl4ck5un

**Comment by sr-gi** [comment]
Hey @bl4ck5un , looks like something is going on with Travis, since the `html` file linked in events is not the one that was generated from the `md` file. I've noticed that yesterday on local server, but I thought it was just me. Has something changed?

**Comment by jimballingall** [comment]
any progress on posting this?

**Comment by bl4ck5un** [comment]
@sr-gi thanks for catching the bug. I fixed it in 43c63ec886202500934c9a49e3eefb5a466832ab.
@jimballingall the page is now updated.

**Comment by sr-gi** [comment]
Sure, no problem.

**Comment by bl4ck5un** [comment]
travis is currently experiencing network problems (cannot download packages). I'll wait for a while for it to self-resolve.

**Comment by jimballingall** [comment]
Thanks for posting, but please reference the v2 I posted above.  This (1) corrected the "session 7" and added/removed a few names (see below)
4:15 - 4:45  Session 7: Vision Stand Up: New Applications and Research Directions - Chair: Andrew Miller

Sarah Meiklejohn - 3 min
Dan Robinson - 3 min
Dahlia Malkhi - 3 min
Patrick McCorry - 3 min
Robbert van Renesse - 3 min
Emin Gun Sirer - 3 min
Ari Juels - 3 min
Andrew Myers - 3 min
Dawn Song - 3 min

(2) added a BOF Session for Sarah at lunch, and 
(3) added the Bar's address. 
Also, please use "Tata Innovation Center" at top of agenda above Breakfast (it says "Cente" now). BoF for "Infratstruc" should read "Infrastructure"...

**Comment by bl4ck5un** [comment]
@sr-gi can you reapply updates based on v2? thanks.

**Comment by jimballingall** [comment]
Is it possible to just use the pdf attached? The formatting of the web page now looks awkward. Also, I moved up the group photo at the bottom of the page to be sure people saw it in the attached.
[IC3 2018 Spring Retreat Agenda and Photos.pdf](https://github.com/bl4ck5un/ic3-website/files/2026937/IC3.2018.Spring.Retreat.Agenda.and.Photos.pdf)

**Comment by sr-gi** [comment]
Sure, I'm quite busy this week and the upcoming one with TA work. I'll catch up on the issues asap.

**Comment by bl4ck5un** [comment]
@jimballingall I tweaked the style a little bit now the pictures looks much better. Can you provide a PDF with only the agenda?

**Comment by jimballingall** [comment]
Please see pdf of agenda attached here:
[IC3 2018 Spring Retreat Final Agenda.pdf](https://github.com/bl4ck5un/ic3-website/files/2035609/IC3.2018.Spring.Retreat.Final.Agenda.pdf)

**Comment by jimballingall** [comment]
Also, please insert this text above the top photo.
"IC3 faculty, students and industry members gather at IC3 Retreats to discuss the major technical challenges, issues and innovative solutions to widespread blockchain adoption."

**Comment by bl4ck5un** [comment]
Fixed. I close this issue now. Please reopen if there are issues.
