### ISSUE TITLE
Create a members-only private page on the IC3 site

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#217]
Hi Fan and Sergi,

This will be to post info for IC3 members. Pre-prints, Retreat presentations, working group docs, etc.

For access, the most common means I know is we would ask individuals to register, and we must approve their registration. I'm open to other ideas...

Every page on the IC3 site should have an unobtrusive button in the upper right had corner that says "Member Login". That would take them to a member log-in page for access.

Thanks,

Jim

**Comment by bl4ck5un** [comment]
@jimballingall Jim I'm closing this issue as it seems resolved. Please reopen if not.
