### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by IttayEyal** [bl4ck5un/ic3-website#237]
Please update the grand challenge category and project list as detailed in the following document: https://docs.google.com/document/d/16IbfRekkUZ4yT98-Vym-roZC3Gj6W7IOOTMMCpkUtKU/edit

ping me for any questions

**Comment by biblioscarlet** [comment]
Does this still need to be done? I'm trying to close old issues.

**Comment by jimballingall** [comment]
Please add the few projects from this doc that are not currently on the website (unless they look redundant - with nearly the same title). Per Ittay: Rename category: Scaling and Performance → Secure Scaling and Performance
