### ISSUE TITLE
Update July 2018 Boot Camp Page

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#238]
Please use the attached version for now. Please arrange the sponsor logos alphabetically, left to right in rows (not taking a whole page like I did :-)  

We will add the video links to the talks when IT provides them. Maybe this coming week.
[IC3 Website Boot Camp 2018 - July 26.docx](https://github.com/bl4ck5un/ic3-website/files/2260010/IC3.Website.Boot.Camp.2018.-.July.26.docx)

**Comment by biblioscarlet** [comment]
[IC3.Website.Boot.Camp.2018.-.July.26.docx](https://github.com/bl4ck5un/ic3-website/files/2284058/IC3.Website.Boot.Camp.2018.-.July.26.docx)

Jim, is this better?

**Comment by jimballingall** [comment]
looks great Veronica, please post it, Thanks!

**Comment by jimballingall** [comment]
Ittay, can you post this?

**Comment by IttayEyal** [comment]
Hi Jim,

I don't edit the page directly. Please ask Fan who's doing that.

Thanks,
Ittay
