### ISSUE TITLE
Update Makefile to work

### ISSUE THREAD

**Issue by sbaks0820** [bl4ck5un/ic3-website#256]
Makefile spawns a `unoconv` listener which never progresses. Process needs to be backgrounded.

**Comment by sbaks0820** [comment]
definitely spoke too soon.... there's a make file in the directory

**Comment by sbaks0820** [comment]
#257

**Comment by bl4ck5un** [comment]
in Travis environment `unoconv -l` is somehow non-blocking. by the way, use of `ods` is due to historical reasons and perhaps not a good idea.
