### ISSUE TITLE
edit the Nov 13 Meetup description

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#267]
Noah Johnson, a PhD student in Computer Science at UC Berkeley, advised by Prof. Dawn Song will talk about Oasis, a platform for privacy-preserving smart contracts at scale. This Meetup is hosted by VMware in Palo Alto, and will be LiveStreamed via Zoom.

[Veronica, please add ', and will be LiveStreamed via Zoom.' to the current description posted now.]

**Comment by jimballingall** [comment]
You misspelled Blockchain so the link does not work.

**Comment by jimballingall** [comment]
You misspelled Blockchain so the link does not work.

**Comment by biblioscarlet** [comment]
I've edited it, should work now. But it will take a few minutes before it hits the website.
