### ISSUE TITLE
Add "Spinoffs and Tech Transfer" page

### ISSUE THREAD

**Issue by ajuels** [bl4ck5un/ic3-website#271]
Add Oasis Labs, ThunderCore, bloxroute, Town Crier to page highlighting commercial impact of IC3

**Comment by sbaks0820** [comment]
I'm not exactly sure which page you are referring to. The only commercial impact page I can interpret is the "Partners" page. Can you link to the page you want it on?

**Comment by biblioscarlet** [comment]
Impact Page created.
