### ISSUE TITLE
update IC3 2019 winter retreat web page

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#274]
Please use this document. Note we have Switzerland mis-spelled on current page.

[IC3 website 2019 Winter Retreat Dec 19.docx](https://github.com/bl4ck5un/ic3-website/files/2696956/IC3.website.2019.Winter.Retreat.Dec.19.docx)

**Comment by jimballingall** [comment]
Please modify the text of the summary on the event page as follows:
IC3 Winter Retreat
February 14-15, 2019 Congress Centre Kursaal Interlaken, Strandbadstrasse 44, 3800 Interlaken, Switzerland
IC3 faculty, students and sponsors gather at IC3 Retreats to discuss the major technical challenges, issues and innovative solutions to widespread blockchain adoption. For registration, information and the agenda, please see **IC3 Retreat Info**

**Comment by jimballingall** [comment]
Please replace the current IC3 Winter Retreat doc with this: 
[IC3.website.2019.Winter.Retreat.Dec.22.pdf](https://github.com/bl4ck5un/ic3-website/files/2705254/IC3.website.2019.Winter.Retreat.Dec.22.pdf)

And for the hyperlink list of local hotels in the new IC3 Winter Retreat doc, please use this doc:
[A sample of lodging accommodations nearby the Congress Centre.pdf](https://github.com/bl4ck5un/ic3-website/files/2705257/A.sample.of.lodging.accommodations.nearby.the.Congress.Centre.pdf)

**Comment by jimballingall** [comment]
The pdf version I attached above did not preserve the hyperlinks in the attached Word doc. Please be sure the hyperlinks operate correctly (and you need to add the hyperlink for the hotel list that is reference therein). Thanks!
[IC3.website.2019.Winter.Retreat.Dec.22.docx](https://github.com/bl4ck5un/ic3-website/files/2721169/IC3.website.2019.Winter.Retreat.Dec.22.docx)

**Comment by biblioscarlet** [comment]
Did you try refreshing the IC3 website? Sometimes it takes a bit to update. I tried it just now and the document pops up and the links are active.

**Comment by jimballingall** [comment]
It is downloading the doc now, but the GitHub link you crated for the list of hotels is not operating. Can you give it an IC3 domain related site?

**Comment by biblioscarlet** [comment]
I have the link in my Google Drive. The hyperlink should work now.
