### ISSUE TITLE
add IC3 Newsletters to Press section

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#278]
IC3 Newsletter - Q1 2019
https://conta.cc/2DdM1Bq

IC3 Newsletter - Upcoming Events - March 2019
https://conta.cc/2Jwunyg

**Comment by jimballingall** [comment]
IC3 Newsletter - Blockchain Camp June 10-16, News, and More - May 2019
https://conta.cc/2HsKGYx

**Comment by biblioscarlet** [comment]
Added
