### ISSUE TITLE
Update Newsletters Section on the Press page

### ISSUE THREAD

**Issue by jimballingall** [bl4ck5un/ic3-website#279]
https://www.initc3.org/press.html

Please use the attached to update the Newsletter section. Drop the "Quarterly" and "Qx" adjectives. I didn't embed the hyperlinks for the latest  3 Newsletters, but please do so on the web page.

[IC3 Newsletters - june 2019.docx](https://github.com/bl4ck5un/ic3-website/files/3331274/IC3.Newsletters.-.june.2019.docx)

**Comment by jimballingall** [comment]
I don't see any changes. Why is this closed?

**Comment by biblioscarlet** [comment]
They were added to the press page last week.

**Comment by biblioscarlet** [comment]
Ah, I see the part that isn't updated, I think that's a different template... Let me figure out how to fix that.
